### ISSUE TITLE
World Cleaner

### ISSUE THREAD

**Issue by rakzhodekams** [open-source-ideas/ideas#196]
For **Educational** Proposes Only - Not only for Children

~ In a Monkey world everything would work like... ~

    ~ Monkey cannot impose his will of Power but can motivate Yours!!

### Intention:

    Learn by Educating Your self

Animated Example: [The Condition of Illusion](https://odicforcesounds.github.io/The-Condition-of-illusion/)

"Each Positive Contribution that Benefit other Living Being may have Economic Value and Social Value as well. The Value
is in the capacity of any person to solve any problem that may be solved by Social Values which care,"

---

## Problems to solve:

Create better relations in society between all living Beings:

Associate Economic Value to what have value as well.

- Rate every Positive Contribution from others.

**Note**: "In Social and Justice Perspective, to ask apologies in a way, where the "victim" feels that the "attacker"
is trully sorry, is rated as a positive **Deed**. By the same concept, all "bad" actions which take any
social responsability as mistakes, can be "fixed", May everyone be OpenSource to their own Source and to everyone else.

1.  Students: Behaviors / Choices
2.  Social: Behaviors / Choices
3.  Professional: Behaviors / Choices

        ~ Don't rate / promote every Negative Contribution from others.

        ~ Discuss / Talk / Present solutions to fix those.

        ~ The Bad behaviors shall not become more important than the good.

        ~ Promote Good behaviors ( at all levels of society and associate value to it )

## Objectives:

- Motivate **World Wide Brands Industry** to pay more attention to their own Business to **care** Social and Nature Principles

1.  Count the number of times each personal characteristic is rated as positive.

        - Just for Fun: How many times I do good things to others?

        - Each employee need to do more than what he/she aims to do. Rate That!

        - Associate Value to each detail, to each singular action.

2.  Each positive point represent one coin.

        - If the difference is in the atittude, then atittudes have value.

        - More than the product it self.

> **TODO**: Build list of human / social characteristics that can be rated.

1. Each positive point shall have associated economic value.

- Points point to the value of one singularity ( good deed )

  - That is the value: It can be exchanged! ("in favor of")

## Rewards for Companies - Industry

1. External Image:

   Public Exposition as group who made X positive contributions to this system above / bellow others.

- Company Characteristics are based in Content and Actions:

  - **Content** is what a Company produce ( products )

  - What can become better ( Healthy Products ) ( social terms )

  - **Actions** is the social activity they promote with their own Time of Work.

  - What kind of Social Actions company promote ( social terms )

2. Internal Image:

- Internal Exposition as individuals who where rated for having positive contributions between colleagues ( commercial terms )

- What are the rate between clients and company employees ( commercial terms )

## Personal Characteristics:

> **TODO**: Social-Behaviors: Recommended-List

- NCP: Nature Care Path: Help plants, clean rivers, etc..

- ACP: Animal Care Path: Walk the dog, help animals, save cats / birds from bad situations but leave them free for the
  next one.

- HCP: Human Care Path: Give food, knowledge, cloths, etc.. Everything that is
  shared by Heart should have more value than the value of the object we share!
  Here we can ask a concept proof from "target", as a way to recognize this transaction.

> **TODO**: Professional-Behaviors: Recommended-List

- Care client: be cool, patient, etc..

## Includes Students and Schools

**Note**: People around the world say that "Time is Money", therefor for each positive result of each who spend Time to
learn and share that knowledge with the teacher, shall earn Money. The same interpretation, shall be added to each who was able to solve a problem. ( logic or
social )

> **TODO**: Student-Behaviors: Recommended-List

- Student-Objectives:
  1. For each Discipline, for each propriety of a discipline, if learned, gain value.
     - How many Books You read. What they are about? What did you learn, etc...
  2. From Students to colleagues, rate positive behaviors, report negative behaviors by **talking** with who produce them.
  3. From Students to Teachers, rate positive behaviors.
  4. From Teachers to Students, rate positive behaviors and proprieties of knowledge, students had demonstrated as gained.

---

"The Value is in the individual who gives a correct answer, not in the **Numeric Expression** which is the **object** we associate value.", while any blockchain can be related to that "numeric expression" as well!

---

## Developers

1. Rate each code contribution that fix your code problems
2. Rate each contribution others do in your work

## Writters

Writers are everywhere. Code Writters and Story Writters.

1. Fixing a mistake or mispell, diserves gratitude. (rate / share)

## Brands Challenge:

- Public or Private groups who represent a Logo

1. Clean Rivers
2. Change Products ( less poluents )
3. Build Green Zones
4. Share Waste
5. Recycle
6. Educate and Motivate other Brands doing the same

## Government Services

- Public or Private groups who represent a Logo ( ALL )

1. Rate behavior from Civilian to Professional
2. Professional rate Civilian Behavior.
3. Urgency Services:
   - For this particular problem we can add a video streaming solution as a Concept Proof.
   - Since it helps professionals to solve by making decisions to any problem they may need to care.
   - If Citizan Help by contributing with their Civic Action, they gain Social Points ( private or public ) each decide
     to their own.
   - To most of the Public Services Governments need access, most of the Times, the KEY members are
     non-public-services, but regular civilians. Be sure You Rate that Civic Action that have Value!!!  
     ( for 112 to police, etc... )
   - Joke?: If you don't find good poeple, become one. Then We All Can.

---

## Eternal License

You are Included in [this](https://art.odicforcesounds.com/pages/License/index.html) World Wide Target Eternal License!

---

So, in social / justice perspectives, people around the world exchange value by helping others in several ways. 
In this aspect, your note about this issue have value ( the value of your attention and the value of your need to interact with this post ) 

The Idea is that ( for this case - between all developers communities ) -> who  fix  / contribute positivitly to someone, and if that someone ( in this case me ) recognize you were helpful, I send your a "numeric expression that represent value" ( 1 ) in the possible categories of your user. 

You spend Time and Energy ( and you did read, so you did process information better than a computer ) 
Good ! ( I value it more than a actual Bitcoin ).

You know, the value is always in the individual who solve a problem.... 

To be more clear, any cryptocoin should only have value when is focused in something above it's own expression. 

I Value choices and actions! 

Normally many can think "how to create a good warrior", while in this case is "how to create good friends", while any warrior can be a good friend and any friend can be a warrior! ;) 

I Focus in the "Good" ... we already have many other examples that focus something bad,

**Comment by james2mid** [comment]
It's interesting getting a peak into your mind with your website and manifest etc, but I don't really understand what the purpose of the project is?

**Comment by james2mid** [comment]
Apologies, I've only just started reading through "Principles of this idea" and I'm liking what I see.

**Comment by remram44** [comment]
I read most of the pages but still have no idea what this is about. Can you add a description (in English) of what the finished product is supposed to be about?

**Comment by rakzhodekams** [comment]
:) As people in github and other hubs, share and fix code that other do. This ( the relation and the value is in the "action" that share / fix ) therefor, have value. The propose of giving value to each contribution even for coding or fix typos in simple text, have value as well. So, in the principle of education process, the coder is studen and teacher at the same time, while both are spending time that should be rewarded for the "student" as well. @remram44 + @james2mid .. isn't a good "deed" to help someone else to become better? So, Like in coding, Life as human behavior in society needs as well that attention, while if is rewarded as well, may the value of it, fix or even make a better society, in this perspective of helping others to become better or at least not worst. .. as a social mechanism is what I considere as "bad & good" at the same time... In fact I am deeply thinking about DELETING the concept of VIDEOS.. while at the same time, it is the only part where even "words" fail to describe what the "Eyes" can see... the news use videos ( as concept proofs ) .. therefor.. we have a privacy problem here... therefor a security problem, but if we think the "positive way", in some details ( as police report / accident report ) is not bad, since it helps the professionals to deal with the problem, while the person who report the problem  should be rewarded for CIVIC actions.. more social promotion and more democratic exposure.. "merit" .. well is a Challenge ( because it touch several social problems ) ... if  we think what can be bad is a terrible challenge, if we think what  can goes right, it is good enoght to go work in. In fact, I think all privacy problems can be jumped, since each one who make the "video report" can expose him/her self or not, but it can be wrong.. For me, more than anything is a "offensive expression" of what life should be, while in china reality and others, this technique is working  fine! .. therefor I build an expression to make others think / feel if is necessary.. I see world wide social behavior not really peaceful, therefor ...

**Comment by remram44** [comment]
Stop spamming. Don't mention people who have stated that they don't care.

**Comment by rakzhodekams** [comment]
> Stop spamming. Don't mention people who have stated that they don't care.
In fact, that was the biggest truth I read. That is why the challenge is crap!! In any case, the mention was with who interact with, because those who don't care, shouldn't interact with something they don't care ( ... ) .. let it flow

**Comment by rakzhodekams** [comment]
where is my reward? :P

**Comment by rakzhodekams** [comment]
And With my own bad example I can point to the idea of this challenge, which aims educate behaviors, giving a reward to those who don't care.. sadly I care.. that is why of thought about.. but in any case, it was a stupid idea! ;)

**Comment by rakzhodekams** [comment]
Why Should Employees should evaluate each others in their work time, and why civilians should evaluate each others in their free time? Well, that was the problem I wish to solve.. in my interpretation, both can evaluate each others to motivate each others to be better with others!

**Comment by rakzhodekams** [comment]
but if you can care u can focus the same crap to something you can.. :D it is a point of view in fact..

**Comment by FredrikAugust** [comment]
What reward are you referring to @rakzhodekams?

Also, please add back the template for the issue so people can get a quick overview of your idea without going to your link.

**Comment by rakzhodekams** [comment]
@FredrikAugust copy and paste the content of that link page in here. 

Thank you for your contribution.

**Comment by KOLANICH** [comment]
I propose to just remove this issue and block its author.

**Comment by FredrikAugust** [comment]
@rakzhodekams Please follow the template. I will close this issue until you do so. And as others have pointed out: please don't tag others who are not involved.
