### ISSUE TITLE
Free Open-Source USB 2.0/3.0 extension pack for VirtualBox

### ISSUE THREAD

**Issue by KOLANICH** [open-source-ideas/ideas#255]
## Project description

While VirtualBox is free software itself, some essential parts, like USB 2.0 passthrough, were moved into a proprietary closed-source paid (for everything except personal, eductional and evaluational use) extension pack. QEMU has an own impl of USB passthrough, it may make sense to make an extension pack plugging QEMU impl into virtualbox plugin. There is a small issue that the framework used for plugins is largely undocumented, but there aresome examples in the repo.

## Relevant Technology
* https://www.virtualbox.org/browser/vbox/trunk/src/VBox/ExtPacks/BusMouseSample
* https://github.com/qemu/qemu/blob/master/hw/usb/

### Complexity

- [x] Advanced - The project requires the user to have a good understanding of all components of the project to contribute

### Required time (ETA)

- [x] Much work - The project will take more than a couple of weeks and serious planning is required

### Categories
- [x] Extension/Plugin/Add-On

**Comment by Bessonov** [comment]
Great request! Personally, I would be fine to buy a license and it would be still cheaper than buying a vmware license. The thing is, that I have no way to buy just one license, because oracle sells it only from 100 units.

For the scope, I would be fine if I would be able attach USB 3.0 devices even with USB 1.0 speed.

**Comment by KOLANICH** [comment]
>Great request!

It's not. Noone owes us anything. It's just a documentation that a need exists, to slightly increase the chance of it being implemented.

>it would be still cheaper than buying a vmware license.

QEMU may fit your needs, recently virtio-fs protocol has been implemented for Windows, allowing sharing host dirs with the guest efficiently. There are still major inconveniences when using QEMU instead of VirtualBox though.

**Comment by Bessonov** [comment]
Well, I'm using [Vagrant](https://www.vagrantup.com/). Despite it supports vmware and hyper-v additionally, it seems like they aren't really usable (disk expansion isn't supported etc.).

**Comment by KOLANICH** [comment]
Not needed anymore. Since 7.0 Oracle has made USB 2.0/3.0 support a part of VirtualBox, ext pack is not needed.

**Comment by Bessonov** [comment]
@KOLANICH great news! Do you have any pointer to it? I wasn't able to find that in the changelog.

**Comment by Bessonov** [comment]
Oh, I see, probably this one:

> Devices: The EHCI and XHCI USB controller devices are now part of the open source base package
