### ISSUE TITLE
A quality 3d game engine for python with good performance

### ISSUE THREAD

**Issue by ns23k** [open-source-ideas/ideas#318]
### Complexity

- [x] Advanced - The project requires the user to have a good understanding of all components of the project to contribute

### Required time (ETA)

- [x] Much work - The project will take more than a couple of weeks and serious planning is required

### Categories
- [x] Frontend/UI
- [x] Developer Tooling
- [x] Design/UX
- [x] AR/VR
- [x] Futuristic Tech/Something Unique

**Comment by KOLANICH** [comment]
>python
>good performance

/0

**Comment by publicsite** [comment]
Hi, have you tried any of the following game engines? [https://en.wikipedia.org/wiki/List_of_game_engines](https://en.wikipedia.org/wiki/List_of_game_engines) Could you go through the list of the ones re. python and explain why they don't already meet the criterea? I am also interested in python game engines. I am interested in using converted scenery from flightgear (see my repo): [https://github.com/publicsite/flightgear_export_scripts](https://github.com/publicsite/flightgear_export_scripts) in a game that is not flightgear.

**Comment by FredrikAugust** [comment]
@Naman23-coder could you please add some more details to the idea?

**Comment by raulmihaila** [comment]
[Godot](https://godotengine.org/) uses a language called GDScript which is close to Python.There is also a project providing python support for Godot https://github.com/touilleMan/godot-python maintained by the Godot community.
