### ISSUE TITLE
Yellow pages for apps/webapps

### ISSUE THREAD

**Issue by rajaParmar** [open-source-ideas/ideas#328]
## Project description

We have a lot of apps/webapps around us that solve problems, but they are sometimes impossible to find. I want to make something that helps people find the app that they need from their vague problem scenarios.

Let me know if something like this already exists!

### Complexity

- [ ] Beginner - This project requires no or little prior knowledge of the technolog(y|ies) specified to contribute to the project
- [ ] Intermediate - The user should have some prior knowledge of the technolog(y|ies) to the point where they know how to use it, but not necessarily all the nooks and crannies of the technology
- [ ] Advanced - The project requires the user to have a good understanding of all components of the project to contribute

### Required time (ETA)

- [ ] Little work - A couple of days
- [ ] Medium work - A week or two
- [x] Much work - The project will take more than a couple of weeks and serious planning is required

### Categories

- [ ] Mobile app
- [ ] IoT
- [ ] Web app
- [ ] Frontend/UI
- [ ] AI/ML
- [ ] APIs/Backend
- [ ] Voice Assistant
- [ ] Developer Tooling
- [ ] Extension/Plugin/Add-On
- [ ] Design/UX
- [ ] AR/VR
- [ ] Bots
- [ ] Security
- [ ] Blockchain
- [ ] Futuristic Tech/Something Unique

**Comment by KaKi87** [comment]
https://old.reddit.com/r/software
https://softwarerecs.stackexchange.com/

**Comment by FredrikAugust** [comment]
Please add the correct tags, @rajaParmar

**Comment by FredrikAugust** [comment]
Should this be a search engine, a forum? Could you add some more information?

**Comment by rajaParmar** [comment]
Want it to be a search engine that can mine data rather than a forum where people have to wait for the result! @FredrikAugust

**Comment by rajaParmar** [comment]
> Please add the correct tags, @rajaParmar
At this point, it is kind of vague as to how would one architect this, hence skipping on the tags for now ... but feel free to add a few if you want to :)

**Comment by FredrikAugust** [comment]
Perhaps you could refine your idea a little bit, and add some suggestions to how it could be resolved, along with some tags?
