### ISSUE TITLE
Hate, Life + Human

### ISSUE THREAD

**Issue by rockyoung** [open-source-ideas/ideas#329]
## Project description
just the oppsite of "Love, Death + Robot".

**Comment by KaKi87** [comment]
Does anyone get it ? I don't.

**Comment by chenasraf** [comment]
Nope

**Comment by itamadev** [comment]
🛑 This repo is supposed to consist of **open-source project ideas**.
I think the author should either read the [README file of the project](https://github.com/open-source-ideas/ideas#readme), 
or you can elaborate on your idea to help understand it better 😃

cc: @rockyoung

**Comment by KOLANICH** [comment]
I think the ones who leave the issues violating the template should be ~~sh~~banned on sight.

**Comment by rockyoung** [comment]
oh, sorry guys, i was drunk...

**Comment by FredrikAugust** [comment]
Hahaha, no worries @rockyoung
