### ISSUE TITLE
Create a class for smoltcp allowing to use it without actually doing io (in sans-io style)

### ISSUE THREAD

**Issue by KOLANICH** [open-source-ideas/ideas#331]
## Project description
I need a python userspace stack (not just a parser, but also a state tracker) for a prototype (which is likely here to stay for a long time, but I intend to rewrite that software  either in Rust or in C++ somewhen), unfortunately the only pure one is under a viral license.

So I have come to idea to write python bindings (`ctypes`-based ones, since they require no (re)compilation of native modules) to https://github.com/smoltcp-rs/smoltcp . Unfortunately it doesn't have the C API I need, but it can be straightforwardly implemented by implementing `phy::Device` and implementing some interface using C API, that I csn use from other languages. Should be easy to implement for anyone skilled in Rust.

While I can do it myself (for me it'll take more time, since I'm a very newbie to Rust), for now I'm (as usual) pretty busy. It'd be nice if it is ready by the time I can work on that project again.

## Relevant Technology

* https://github.com/smoltcp-rs/smoltcp

### Complexity

- [x] Beginner - This project requires no or little prior knowledge of the technolog(y|ies) specified to contribute to the project

### Required time (ETA)

- [x] Little work - A couple of days

**Comment by FredrikAugust** [comment]
I am attaching the "Developer Tooling" label just so it has a category
