### ISSUE TITLE
Improve Idea Template

### ISSUE THREAD

**Issue by kaustav202** [open-source-ideas/ideas#335]
The template is great overall, but I have a suggestion to improve it further. If a tag of popular tech is also added, it will be more informative to potential contributors if it's in line with their skill-set or interested technologies.

**Comment by FredrikAugust** [comment]
Glad to hear! Could you perhaps open a discussion instead of an issue, and then it could be discussed further there?

**Comment by KOLANICH** [comment]
I guess it should be a PR rather than a discussion.

**Comment by FredrikAugust** [comment]
If there is a concrete suggestion for changes to the PR template, then I agree. However, I think regardless if there is a concrete template suggestion, or a more abstract change, it would be nice to have a discussion surrounding the proposed change.

**Comment by KOLANICH** [comment]
PRs have space for discussions around proposed changes
