### ISSUE TITLE
An alternative to spreadsheet software

### ISSUE THREAD

**Issue by juanmad** [open-source-ideas/ideas#351]
I always think that it would be really cool to have something like excel, but instead of using functions perhaps you can use python code to perform a calculation on that cell and drag around it like in excel. Why that, because nesting functions and conditions is so ugly, messy, annoying, etc the way all spreadsheets do it just with lambdas.

I don't think everything should be from scratch though. LibreOffice Calc is free software and maybe can be modified somehow and perhaps just including numpy and integrate it into a spreadsheet python software would be cool. No need to rewrite what's already have been written. While also fixing all shortfalls of spreadsheets software that uses lambdas, who ever though that was a good idea..

**Comment by KOLANICH** [comment]
1. You don't follow the template. It is disrespect to the whole community and your issue will probably be closed if you don't fix it. I have even created software to do it automatically (and when I get how GitHub Actions cache works (I need it to store statistics on offenders somewhere, blocking people for accidentially violating rules is not right, there should be a threshold to block only the recidivists), it would be able to block users too).
2. Spreadsheets are usually mess. If one needs a table, he can probably use pandas + Jupyter Notebook to visualize it.

**Comment by KOLANICH** [comment]
P.S. I usually use spreadsheet software when I need to compose a dataset from a bunch of heterogenous sources. It is easier to copy data into cells than to a TSV text file.

**Comment by FredrikAugust** [comment]
As mentioned by @KOLANICH, please follow the template. You can tag me once you've updated your description to follow the template. I will close the issue until it's been fixed.

**Comment by virtadpt** [comment]
I think [pySpread](https://pyspread.gitlab.io/) might be what you're looking for.
