### ISSUE TITLE
Opensql Node.js ORM

### ISSUE THREAD

**Issue by TREER00T** [open-source-ideas/ideas#356]
## Project description

The orm project is only about understanding and analyzing how orms work. This project named opensql is implemented in this [repository](https://github.com/opensql-org/opensql) and it currently supports three famous databases (mysql, postgres, microsoft sql server).

## Relevant Technology

This project is currently implemented for typescript and javascript using unused telecommunications, only the daemons of each of the mentioned databases are used for connection and query.

## Complexity and required time

The learning time is very short, you can learn the source code and how to use it in less than 1 day

### Complexity

- [x] Beginner - This project requires no or little prior knowledge of the technolog(y|ies) specified to contribute to the project
- [ ] Intermediate - The user should have some prior knowledge of the technolog(y|ies) to the point where they know how to use it, but not necessarily all the nooks and crannies of the technology
- [ ] Advanced - The project requires the user to have a good understanding of all components of the project to contribute

### Required time (ETA)

- [x] Little work - A couple of days
- [ ] Medium work - A week or two
- [ ] Much work - The project will take more than a couple of weeks and serious planning is required

### Categories

- [ ] Mobile app
- [ ] IoT
- [ ] Web app
- [ ] Frontend/UI
- [ ] AI/ML
- [ ] APIs/Backend
- [ ] Voice Assistant
- [x] Developer Tooling
- [ ] Extension/Plugin/Add-On
- [ ] Design/UX
- [ ] AR/VR
- [ ] Bots
- [ ] Security
- [ ] Blockchain
- [ ] Futuristic Tech/Something Unique

**Comment by marcellus-ku-283** [comment]
I want to contribute to this project. How I can start? Can you guide me on that?

I have 5+ years of industrial experience and now want to contribute to open-source projects in my free time.
My prior experience is in PHP. But I am a versatile developer and comfortable with any language and framework.

Thanks

**Comment by TREER00T** [comment]
Hello, thank you for choosing this project for contribution. As you can see, this project is a combination of two popular languages, JS and TS. To start, you can visit the repository at this address, clone the repository, and then refer to the project documentation. Do the necessary steps to setup the project and finally send your changes along with a pull request, then the final review of the changes will be done with the main repository.

It is good to read the tests related to the project before starting the changes so that you have a better understanding of what is happening behind it

Useful links:

[Documentation](https://docs-opensql.vercel.app/)
[Internal Tests](https://github.com/opensql-org/opensql/tree/main/test)
[External Test](https://github.com/opensql-org/opensql/tree/main/lib/sql-parser/test)

**Comment by prophet1906** [comment]
I think [sequelize](https://github.com/sequelize/sequelize) is already a very feature-rich ORM that supports advanced features for many databases. I don't know if reimplementing the same will add any value.

**Comment by TREER00T** [comment]
Yes, I completely agree with you, but this project is written only to understand and analyze what orms do and how they are implemented.

**Comment by SD191100** [comment]
can I get assigned to this project? I am a beginner and want to learn new things as well as start my contributions with a particular project. I know javascript and will try to create this project.

**Comment by TREER00T** [comment]
@SD191100 Yes, you can participate in the project
