### ISSUE TITLE
Video File Audio Track Language Identifier

### ISSUE THREAD

**Issue by crosenblum** [open-source-ideas/ideas#366]
## Project description

This project focuses on developing a language identification system for video files. Many video files have inaccurate metadata to indicate which language each audio track is in. 

If you have 100's or 1000's of such files, the only current process available is to manually play each video file and identify the language in each track, and there is no easy way to modify the audio track language in the video file metadata.

The goal of this project is to provide a CLI/CMD utility that can both identify the correct audio language in each audio track, and modify the metadata, 

## Relevant Technology

I am only going to guess, this will have be some derivative of ffmpeg or ffprobe.  

## Complexity and required time

This will be complex because of the endless variety of spoken languages of mankind, and that video files may have any kind of language encoding, of which the metadata will be missing or incorrect.

Also it has to be a efficient program, as this could be used on 100's or 1000's of video files to fix the audio language metadata.

### Complexity

This will require an intermediate level of knowledge of ffmpeg, ffprobe and cli/cmd video file metadata, and how to efficiently identify each audio track language.

This may not yet be possible, or requires immense hardware resources, or there may be a genius who can create an efficient solution, that anyone may use.

### Required time (ETA)

This could be a 3 weeks to a couple months of work. 

### Categories

This is a CLI/CMD app that can be used in Windows or Linux to process video files, to correct audio track language metadata.

**Comment by KaKi87** [comment]
Additionally to being complex and time-consuming, it's also very niche.

> Many video files have inaccurate metadata to indicate which language each audio track is in.

Where ?

**Comment by crosenblum** [comment]
If you download a video file, from somewhere, very often, the metadata of the audio tracks indicating which language it is, is either inaccurate or missing. Making it very hard to make your preferred language the default or to know which language is supported in the video file.

All I want to do is fix the metadata by correctly identify the spoken language on the audio track. However there is no way to do that.

You can use tools like ffprobe to see what the metadata reveals, but very often is incorrect or missing.

That is why I requested a tool to help solve this problem.

**Comment by KaKi87** [comment]
> If you download a video file, from somewhere, very often, the metadata of the audio tracks indicating which language it is, is either inaccurate or missing.

I'm afraid I never encountered this outside of rare human errors, which is why I'm asking where, for example, are you encountering this.

The only instance of recurring metadata issues I observed is with missing 3D.

**Comment by crosenblum** [comment]
Many people have a media server, such as Jellyfin, Plex, etc.

Sometimes the quality of the video sources is lacking.

In that they have multiple languages as audio tracks, but either not your preferred language, or the metadata indicating which language they are in, is missing or incorrect.

Rather than having a manual process of having to listen for many many different video files, would be nice to have a utility that can correctly identify the spoken language on each audio track, and then fix the metadata.

Then you can know if the video file is usable aka it has audio in your preferred language.

I thought this was a worthy technical challenge if possible. It may not be, or may require heavy hardware resources or complicated ai or cloud programming.

In the end I am hoping for an utility like ffprobe that can identify correctly all spoken languages and fix the metadata.

If this still makes no sense, because you have not experienced this situation, I am not sure what else I can do to describe it.

**Comment by KaKi87** [comment]
Yeah I've used Kodi and Plex.
But those are used to sort files, but files must be downloaded from somewhere.
My question is, where do you download files that lack metadata ?

**Comment by crosenblum** [comment]
I am only interested in discussing this as a technical problem that needs to be solved.

Where anyone downloads videos is not an area of discussion that should be made in a public forum.

**Comment by KaKi87** [comment]
Well, I can prove that, on best-known sources, most video files don't lack metadata, so unless you prove otherwise, what would motivate a developer ?

Additionally, knowing could reveal an XY problem, e.g. video files lack metadata because of a platform-related or uploader-related issue that could be fixed much more efficiently than on the downloader's side, which, by the way, wouldn't benefit the community as every user would have to do it to get the same result.
