### ISSUE TITLE
Repo alternative

### ISSUE THREAD

**Issue by luc-git** [open-source-ideas/ideas#376]
Because the project seems to be discontinued I made a repo to share your ideas. https://github.com/open-source-suggestions/ideas
This repo is a website made by hugo. So the ideas will be added with markdown files

**Comment by KaKi87** [comment]
Does this repo require maintenance ?

I don't think so.

On the contrary, I'd rather post somewhere managed by nobody, than somewhere managed by someone wanting the existing the community to join them rather than stay.

**Comment by sygint** [comment]
Yeah, we don't need to fragment the entire fuctional, active repo because a new one uses hugo and markdown.

It'd be interesting to potentially see a static site generated out of this existing template, thought, perhaps? I'm not sure I see the value in that, though.

**Comment by KaKi87** [comment]
Yep, nothing prevents from using the GitHub API to get this repo's issues and return web pages out of it.

Not even necessarily statically, as client-side `fetch` would totally work.

**Comment by FredrikAugust** [comment]
Hi! Maintainer here. I've been a bit lazy updating the tags but I'll try to keep up going forward. If you want to make a static website displaying the data from this repo then feel free! It's also open source so if you feel like something should be changed then I'm open for suggestions.

**Comment by FredrikAugust** [comment]
I'm also closing this as it's not an idea and we have a discussions page for things like this:)
