### ISSUE TITLE
Fully open sourced implementation of the Spatial Web standard

### ISSUE THREAD

**Issue by timsandgren** [open-source-ideas/ideas#378]
The Spatial Web foundation is promoting a standard for web 3.

There is a discussion within the foundation about how much of if should be open sourced.

Here is an idea to create an open source community around this inititative.

This is a public summary of the standard:
https://drive.google.com/file/d/1sGMU3bwxeGhWNiMXfVciQx5jDph2uxxC/view

It is possible to join this working group of the IEEE to learn more about this standard development.

https://sagroups.ieee.org/2874/

**Comment by FredrikAugust** [comment]
Hi, please use the included format when creating an idea. Thanks for your contribution:)
