### ISSUE TITLE
An App/Web App where people can sell their own homes without having to go through an estate agent

### ISSUE THREAD

**Issue by mmacdo54** [open-source-ideas/ideas#384]
## Project description

Apps like Rightmove already exist but house listings are direct from estate agents. In the days of old people used to sell their houses themselves but if they could list it themselves with some links to what other things they need to sell their home like a home report etc that would be cool. I have dev experience so would be cool to get some other folks that would be willing to join on the journey?

## Relevant Technology

- Mobile: React Native (Expo) or PWA
- Web: HTMX/React easy on this one
- API: Golang or Nodejs

### Complexity

- [ ] Beginner - This project requires no or little prior knowledge of the technolog(y|ies) specified to contribute to the project
- [x] Intermediate - The user should have some prior knowledge of the technolog(y|ies) to the point where they know how to use it, but not necessarily all the nooks and crannies of the technology
- [ ] Advanced - The project requires the user to have a good understanding of all components of the project to contribute

### Required time (ETA)

- [ ] Little work - A couple of days
- [ ] Medium work - A week or two
- [x] Much work - The project will take more than a couple of weeks and serious planning is required

### Categories

- [x] Mobile app
- [ ] IoT
- [x] Web app
- [x] Frontend/UI
- [ ] AI/ML
- [x] APIs/Backend
- [ ] Voice Assistant
- [ ] Developer Tooling
- [ ] Extension/Plugin/Add-On
- [x] Design/UX
- [ ] AR/VR
- [ ] Bots
- [ ] Security
- [ ] Blockchain
- [ ] Futuristic Tech/Something Unique

**Comment by FredrikAugust** [comment]
Hi, did you finish this?
