### ISSUE TITLE
Save the world

### ISSUE THREAD

**Issue by jjnevis** [open-source-ideas/ideas#386]
## Project description

If anyone is going to achieve this (saving the world), it will be "techies". I love us all and we will inherit the earth, just as soon as we've organised ourselves well enough to figure that out how to achieve it.

Don't worry - I'm not expecting us all to be able to process this message, I just need enough of us to get it - it's okay, if you are the sort of person that understands everything and doesn't understand why others don't, then listen up...

This is the dawn of the intelligencia, you know who you are, we just need to connect with each other.

## Relevant Technology

Write what technology is relevant:
All technologies are relevant and none of them, what's relevant is that people are engaged with saving the planet.

What language:
The language that promotes best communication.

what platform:
I'm going with "github.com/open-source-ideas"

any particular library/framework/existing project it is based on:
humanity to date

### Complexity

- [ x] Beginner - This project requires no or little prior knowledge of the technolog(y|ies) specified to contribute to the project
- [ ] Intermediate - The user should have some prior knowledge of the technolog(y|ies) to the point where they know how to use it, but not necessarily all the nooks and crannies of the technology
- [ ] Advanced - The project requires the user to have a good understanding of all components of the project to contribute

### Required time (ETA)

- [ ] Little work - A couple of days
- [ ] Medium work - A week or two
- [x ] Much work - The project will take more than a couple of weeks and serious planning is required

### Categories

- [ ] Mobile app
- [ ] IoT
- [ ] Web app
- [ ] Frontend/UI
- [ ] AI/ML
- [ ] APIs/Backend
- [ ] Voice Assistant
- [ ] Developer Tooling
- [ ] Extension/Plugin/Add-On
- [ ] Design/UX
- [ ] AR/VR
- [ ] Bots
- [ ] Security
- [ ] Blockchain
- [ x] Futuristic Tech/Something Unique

**Comment by KaKi87** [comment]
What ?

- I'm a techie and I don't understand this ;
- No one understands everything ;
- If one lies to themselves into believing they understand everything, then we shouldn't count on them to make the world a better place ;
- Technology can improve the world but not save it ;
- Anyone thinking it can shouldn't be counted on either ;
- Technology doesn't only rely on engineers and technicians, but also everyone else.

**Comment by jjnevis** [comment]
Too many points to respond to at once, but here goes...
>>> What ?
I'm proposing we start a conversation to save the world.

>>> I'm a techie and I don't understand this ;
OK, let's see if we can get you to understand:
we need to save the world and I think you are the solution, so how do we frame the problem so that you can understand it?

>>> No one understands everything ;
yep, but together we can

>>> If one lies to themselves into believing they understand everything, then we shouldn't count on them to make the world a better place ;
Ok

>>> Technology can improve the world but not save it ;
yup, so what can save the world?

>>> Anyone thinking it can shouldn't be counted on either ;
expand please.

>>> Technology doesn't only rely on engineers and technicians, but also everyone else.
totally! let's get everyone involved in saving the world!

it only takes people like you to get involved and we can fix it, I totally believe that.

**Comment by jjnevis** [comment]
Let's start with a simple:
1) we collectively agree to cooperate,
2) we tax "bads" not "goods"
3) tax revenues collected are invested in "goods"

**Comment by Androz2091** [comment]
Yes but no one will want to be in onus unfortunately so it does not work

**Comment by FredrikAugust** [comment]
I'm closing this as not relevant. Sorry about that.

**Comment by KaKi87** [comment]
> you are the solution

We are not.

> so what can save the world?

People.

The technology doesn't do good if people doesn't use it for good.

Look at the blockchain, and machine learning : those things were created to do good, but they're currently wasted by greedy people.

Those are the most popular examples, but there are plenty more in history : everything scientists create gets corrupted by commercial and military people.

**Comment by jjnevis** [comment]
> Yes but no one will want to be in onus unfortunately so it does not work

Looks like you've done your homework on me! 😁

**Comment by KaKi87** [comment]
> saving the world is "not relevant"?

It's not relevant to this forum.

**Comment by jjnevis** [comment]
> > saving the world is "not relevant"?
> 
> It's not relevant to this forum.

"Open-source-ideas", are you restricting this to OS software ideas? Open source is easy bigger than just software.

**Comment by jjnevis** [comment]
Nah, that's cool, leave it closed. 
Cheers
Jay
