### ISSUE TITLE
Rescue productive apps

### ISSUE THREAD

**Issue by jimscott-cyber** [open-source-ideas/ideas#389]
### Complexity

- [ ] Beginner - This project requires no or little prior knowledge of the technolog(y|ies) specified to contribute to the project
- [ ] Intermediate - The user should have some prior knowledge of the technolog(y|ies) to the point where they know how to use it, but not necessarily all the nooks and crannies of the technology
- [ ] Advanced - The project requires the user to have a good understanding of all components of the project to contribute

### Required time (ETA)

- [ ] Little work - A couple of days
- [ ] Medium work - A week or two
- [ ] Much work - The project will take more than a couple of weeks and serious planning is required

### Categories

- [ ] Mobile app
- [ ] IoT
- [ ] Web app
- [ ] Frontend/UI
- [ ] AI/ML
- [ ] APIs/Backend
- [ ] Voice Assistant
- [ ] Developer Tooling
- [ ] Extension/Plugin/Add-On
- [ ] Design/UX
- [ ] AR/VR
- [ ] Bots
- [ ] Security
- [ ] Blockchain
- [ ] Futuristic Tech/Something Unique

**Comment by jimscott-cyber** [comment]
NextDNS is an example of a very good app that got lost in the App Store for reasons unknown. You simply sign in to NextDNS on the web add a profile to device DNS settings from there wow a free version analytics logs filters blocklists more. This is an example of apps that can be saved. Pardon the pun.

**Comment by FredrikAugust** [comment]
Hi, thanks for your contribution. Could you please fill out the template and explain what your idea is? Thanks!
