### ISSUE TITLE
Listary search alternative that hooks into all dialogue boxes (at least the standard ones) and finds what you want.

### ISSUE THREAD

**Issue by ibay770** [open-source-ideas/ideas#392]
Something like  [Listary](https://www.listary.com/) but something that works. Up to version 5, it used t be able to search for files and stuff within boxes (say like typing windows in the services.msc , would automatically highlight and jump to the selected entry.) Unfortunately they have dropped support for that in the latest version and 5 is stll buggy so I'm wondering if its possible to recreate something like that, that also does the same thing with the modern WinUI elements too.

**Comment by FredrikAugust** [comment]
Hi. Thanks for your contribution. Please use the template provided to fill out your idea:)

**Comment by ibay770** [comment]
Perfect. Filled it out. Hope it works. https://github.com/open-source-ideas/ideas/issues/392
